# Generated by Django 4.1.3 on 2022-11-21 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prices', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='price',
            options={'ordering': ['created'], 'verbose_name': 'precio', 'verbose_name_plural': 'precios'},
        ),
    ]
